### ISSUE TITLE
Unknown command 'get_layer_features'

### ISSUE THREAD

**Issue by lchia** [jkrause314/fg_without#1]
Dear Jon，
When I run your code, I have an error like this: 
     Unknown command 'get_layer_features'
     Error in extract_caffe (line 54)
     features = caffe('get_layer_features', {input_images}, options.layer);...
Did I use a wrong version of caffe?
Thank you.
by Li Chenghua

**Comment by jkrause314** [comment]
Thanks for the issue. I used a modified version of matcaffe which I've now included in the repo. Let me know if that doesn't work for you!

**Comment by lchia** [comment]
I'm sorry, Jon. It still doesn't work and returns the same error. I just replaced the "matcaffe.cpp" in "caffe-rc2/matlab/caffe" and "make matcaffe" in the terminal. Did I missed something? Thank you.

**Comment by jkrause314** [comment]
Make sure it actually compiles (you should see caffe.mexa64 update) -- you can do this by e.g. doing a make clean of caffe beforehand. I've just tested this out and it should work.

**Comment by lchia** [comment]
Nice! Nice! It's wonderful, Jon. It worked and that error disappeared. I just closed my matlab and did all steps again. It's amazing. Thanks very much, Jon. It's very very nice of you.
